apiVersion: v1
kind: PersistentVolume
metadata:
  name: gceRedmine
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  gcePersistentDisk: 
    fsType: "ext4" 
    pdName: "pd-disk-1"
  #nfs:
  #  server: 10.132.0.2
  #  path: "/data/nfs/redmine"
