kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: redmine
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  zone: europe-west1-d
  #zones: us-central1-a, us-central1-b, us-east1-b  
  fsType: ext4
