apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  generation: 4
  labels:
    name: arch.prod.pod.newred
    version: "1"
  name: arch.prod.depl.newred
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: arch.prod.pod.newred
      version: "1"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: arch.prod.pod.newred
        version: "1"
    spec:
      volumes:
        - name: persistent-storage
          gcePersistentDisk:
            pdName: redmine-disk
            fsType: ext4
      containers:
      - env:
        - name: REDMINE_DB_USERNAME
          value: redmine
        - name: REDMINE_DB_MYSQL
          value: arch-prod-srv-mysql
        - name: REDMINE_DB_PASSWORD
          value: ChuuutTh1sIs@S3cret
        image: eu.gcr.io/precom-obseques/arch/redmine:20170217-72dc30f-prod
        imagePullPolicy: IfNotPresent
        name: redmine
        ports:
        - containerPort: 3000
          hostPort: 3001
          protocol: TCP
        readinessProbe: 
          exec:
            command:
              - /bin/ls
              - /root/
          initialDelaySeconds: 60
          successThreshold: 1
          periodSeconds: 60
        #  httpGet:
        #    path: /login
        #    port: 3000
        #  initialDelaySeconds: 600
        #  successThreshold: 1
        #  periodSeconds: 600
        #readinessProbe:
        #  httpGet:
        #    path: /login
        #    port: 3000
        #  initialDelaySeconds: 5
        #  timeoutSeconds: 1
        #  periodSeconds: 15
        #livenessProbe:
        #  httpGet:
        #    path: /login
        #    port: 3000
        #  initialDelaySeconds: 15
        #  timeoutSeconds: 1
        #  periodSeconds: 15
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - name: persistent-storage
            mountPath: "/usr/src/redmine/files/"
            readOnly: false
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
