apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: default
spec:
  containers:
    - name: front-end
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - montPath: "/usr/share/nwginx/"
